### ISSUE TITLE
Improve packaging: missing __init__.py file in the cliffordlayers package

### ISSUE THREAD

**Issue by moradza** [microsoft/cliffordlayers#1]
I have encountered an issue while trying to install and import the cliffordlayers package from the GitHub repository. The package appears to be missing the __init__.py file, which is necessary for exposing the package correctly during installation.

As a result, after installing the package using pip install git+https://github.com/microsoft/cliffordlayers.git, the import cliffordlayers command fails to work in Python.

To resolve this issue, consider adding an __init__.py file to the root directory of the cliffordlayers package and modules inside it. This will enable Python to recognize the package structure and allow users to import it successfully.

**Comment by rejuvyesh** [comment]
Thanks for bringing this to our notice! Will cut a release soon.
