### ISSUE TITLE
Questions about clifford_kernel.

### ISSUE THREAD

**Issue by xwqtju** [microsoft/cliffordlayers#11]
May I inquire, what is the difference between get_2d_clifford_kernel and these two get_2d_clifford_rotation_kernel? Additionally, is it possible to construct a complete 4D PGA kernel, similar to how get_3d_clifford_kernel is defined?

**Comment by rejuvyesh** [comment]
You might find our papers on [Clifford Layers](https://arxiv.org/pdf/2209.04934.pdf) and [Geometric Clifford Layers](https://arxiv.org/pdf/2302.06594.pdf). On a high level, `get_2d_clifford_kernel` implements the standard Clifford interpretation of CNNs replacing vector multiplication with multi-vector geometric product, while `get_2d_clifford_rotation_kernel` is the Clifford interpretation of ["Quaternion CNNs"](https://arxiv.org/abs/1903.00658) and applies a rotational transform. This always seemed to do better in our experiments than the standard Clifford CNN. In the GCAN paper we provide a better understanding of _why_ (better preservation/transformation of geometric properties).

**Comment by xwqtju** [comment]
Thx! It seems that a deeper understanding of GCAN requires more time.
