### ISSUE TITLE
The error was raised

### ISSUE THREAD

**Issue by xwqtju** [microsoft/cliffordlayers#5]
![image](https://github.com/microsoft/cliffordlayers/assets/29054010/f77dc72f-d216-4abe-97d0-679ca4d6d467)
Hi！There is problem raised when I import CliffordAlgebra. Would it be possible for you to check the source code again?

**Comment by rejuvyesh** [comment]
Ah, what python version are you on? The issue is that this kind of types are only allowed on more recent versions of python. We should probably using `Tuple` from `typing` if we want to support older python versions. Thanks for bringing this to our notice.

**Comment by xwqok** [comment]
Python version 3.8.16 is being used by me. Thank you very much for your assistance.

**Comment by xwqtju** [comment]
> Ah, what python version are you on? The issue is that this kind of types are only allowed on more recent versions of python. We should probably using `Tuple` from `typing` if we want to support older python versions. Thanks for bringing this to our notice.

Python version 3.8.16 is being used by me. Thank you very much for your assistance.

**Comment by rejuvyesh** [comment]
I've enabled CI and fixed this issue in 676c0d912bb23e4d9d9e9808c204be26fe24e44d.
